# Generated by Django 4.2.2 on 2023-07-12 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_teams'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='teams',
            new_name='team',
        ),
    ]
